// public/env.js
window.env = {
    REACT_APP_FIREBASE_API_KEY: 'AIzaSyAZJY1TO_FaZK826Ly3zdRTm_eIfXJakBo',
    REACT_APP_FIREBASE_AUTH_DOMAIN: 'sounds-of-life.firebaseapp.com',
    REACT_APP_FIREBASE_PROJECT_ID: 'sounds-of-life',
    REACT_APP_FIREBASE_STORAGE_BUCKET: 'sounds-of-life.firebasestorage.app',
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID: '509209012765',
    REACT_APP_FIREBASE_APP_ID: '1:509209012765:web:fd9d7a5abd51c67fc8f4f4',
    REACT_APP_FIREBASE_MEASUREMENT_ID: 'G-HJ85SP240N'
  };